######################################################################
##
## Filename: bin2dec.udo
## Created on: Wed Aug 24 03:13:48 CST CST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
#force -freeze sim:/bin2dec/clk 1 0, 0 {10000 ps} -r 20000
