######################################################################
##
## Filename: bin2bcd.udo
## Created on: Fri Aug 26 01:15:16 CST CST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
