######################################################################
##
## Filename: dcm_90m.udo
## Created on: Wed Aug 31 11:34:44 CST CST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
