######################################################################
##
## Filename: dis_state.udo
## Created on: Sun Aug 28 01:15:48 CST CST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
