######################################################################
##
## Filename: dis_ram.udo
## Created on: Sun Aug 28 07:42:47 CST CST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
force -freeze sim:/dis_ram/mode 00000001 0
force -freeze sim:/dis_ram/rst_w 1 0
force -freeze sim:/dis_ram/clk_w 1 0, 0 {50 ps} -r 100
