######################################################################
##
## Filename: keyboard.udo
## Created on: Fri Aug 26 05:18:40 CST CST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
force -freeze sim:/keyboard/clk 1 0, 0 {10000 ps} -r 20000
force -freeze sim:/keyboard/rst_n 1 0
