######################################################################
##
## Filename: main.udo
## Created on: Tue Aug 23 19:06:52 CST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
force -freeze sim:/main/clk_ex 1 0, 0 {10000 ps} -r 20000	
