######################################################################
##
## Filename: Module.udo
## Created on: Fri Aug 26 09:21:43 CST CST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
